/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2019-08-28 06:00:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1562892924884L));
    _jspx_dependants.put("jar:file:/C:/Users/SSG/Documents/springPJT/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HFSF/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("  <meta charset=\"utf-8\">\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("  <meta name=\"description\" content=\"\">\n");
      out.write("  <meta name=\"author\" content=\"\">\n");
      out.write("\n");
      out.write("  <title>SB Admin - Dashboard </title>\n");
      out.write("\n");
      out.write("  <!-- Custom fonts for this template-->\n");
      out.write("  <link href=\"/resources/bootstrap/vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("\n");
      out.write("  <!-- Page level plugin CSS-->\n");
      out.write("  <link href=\"/resources/bootstrap/vendor/datatables/dataTables.bootstrap4.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("  <!-- Custom styles for this template-->\n");
      out.write("  <link href=\"/resources/bootstrap/css/sb-admin.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body id=\"page-top\">\n");
      out.write("\n");
      out.write("  <nav class=\"navbar navbar-expand navbar-dark bg-dark static-top\">\n");
      out.write("\n");
      out.write("    <a class=\"navbar-brand mr-1\" href=\"index.html\">Start Bootstrap</a>\n");
      out.write("\n");
      out.write("    <button class=\"btn btn-link btn-sm text-white order-1 order-sm-0\" id=\"sidebarToggle\" href=\"#\">\n");
      out.write("      <i class=\"fas fa-bars\"></i>\n");
      out.write("    </button>\n");
      out.write("\n");
      out.write("    <!-- Navbar Search -->\n");
      out.write("    <form class=\"d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0\">\n");
      out.write("      <div class=\"input-group\">\n");
      out.write("        <input type=\"text\" class=\"form-control\" placeholder=\"Search for...\" aria-label=\"Search\" aria-describedby=\"basic-addon2\">\n");
      out.write("        <div class=\"input-group-append\">\n");
      out.write("          <button class=\"btn btn-primary\" type=\"button\">\n");
      out.write("            <i class=\"fas fa-search\"></i>\n");
      out.write("          </button>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </form>\n");
      out.write("\n");
      out.write("    <!-- Navbar -->\n");
      out.write("    <ul class=\"navbar-nav ml-auto ml-md-0\">\n");
      out.write("      <li class=\"nav-item dropdown no-arrow mx-1\">\n");
      out.write("        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"alertsDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n");
      out.write("          <i class=\"fas fa-bell fa-fw\"></i>\n");
      out.write("          <span class=\"badge badge-danger\">9+</span>\n");
      out.write("        </a>\n");
      out.write("        <div class=\"dropdown-menu dropdown-menu-right\" aria-labelledby=\"alertsDropdown\">\n");
      out.write("          <a class=\"dropdown-item\" href=\"#\">Action</a>\n");
      out.write("          <a class=\"dropdown-item\" href=\"#\">Another action</a>\n");
      out.write("          <div class=\"dropdown-divider\"></div>\n");
      out.write("          <a class=\"dropdown-item\" href=\"#\">Something else here</a>\n");
      out.write("        </div>\n");
      out.write("      </li>\n");
      out.write("      <li class=\"nav-item dropdown no-arrow mx-1\">\n");
      out.write("        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"messagesDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n");
      out.write("          <i class=\"fas fa-envelope fa-fw\"></i>\n");
      out.write("          <span class=\"badge badge-danger\">7</span>\n");
      out.write("        </a>\n");
      out.write("        <div class=\"dropdown-menu dropdown-menu-right\" aria-labelledby=\"messagesDropdown\">\n");
      out.write("          <a class=\"dropdown-item\" href=\"#\">Action</a>\n");
      out.write("          <a class=\"dropdown-item\" href=\"#\">Another action</a>\n");
      out.write("          <div class=\"dropdown-divider\"></div>\n");
      out.write("          <a class=\"dropdown-item\" href=\"#\">Something else here</a>\n");
      out.write("        </div>\n");
      out.write("      </li>\n");
      out.write("      <li class=\"nav-item dropdown no-arrow\">\n");
      out.write("        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"userDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n");
      out.write("          <i class=\"fas fa-user-circle fa-fw\"></i>\n");
      out.write("        </a>\n");
      out.write("        <div class=\"dropdown-menu dropdown-menu-right\" aria-labelledby=\"userDropdown\">\n");
      out.write("          <a class=\"dropdown-item\" href=\"#\">Settings</a>\n");
      out.write("          <a class=\"dropdown-item\" href=\"#\">Activity Log</a>\n");
      out.write("          <div class=\"dropdown-divider\"></div>\n");
      out.write("          <a class=\"dropdown-item\" href=\"#\" data-toggle=\"modal\" data-target=\"#logoutModal\">Logout</a>\n");
      out.write("        </div>\n");
      out.write("      </li>\n");
      out.write("    </ul>\n");
      out.write("\n");
      out.write("  </nav>\n");
      out.write("\n");
      out.write("  <div id=\"wrapper\">\n");
      out.write("\n");
      out.write("    <!-- Sidebar -->\n");
      out.write("    <ul class=\"sidebar navbar-nav\">\n");
      out.write("      <li class=\"nav-item active\">\n");
      out.write("        <a class=\"nav-link\" href=\"index.html\">\n");
      out.write("          <i class=\"fas fa-fw fa-tachometer-alt\"></i>\n");
      out.write("          <span>Dashboard</span>\n");
      out.write("        </a>\n");
      out.write("      </li>\n");
      out.write("      <li class=\"nav-item dropdown\">\n");
      out.write("        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"pagesDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n");
      out.write("          <i class=\"fas fa-fw fa-folder\"></i>\n");
      out.write("          <span>Pages</span>\n");
      out.write("        </a>\n");
      out.write("        <div class=\"dropdown-menu\" aria-labelledby=\"pagesDropdown\">\n");
      out.write("          <h6 class=\"dropdown-header\">Login Screens:</h6>\n");
      out.write("          <a class=\"dropdown-item\" href=\"login.html\">Login</a>\n");
      out.write("          <a class=\"dropdown-item\" href=\"register.html\">Register</a>\n");
      out.write("          <a class=\"dropdown-item\" href=\"forgot-password.html\">Forgot Password</a>\n");
      out.write("          <div class=\"dropdown-divider\"></div>\n");
      out.write("          <h6 class=\"dropdown-header\">Other Pages:</h6>\n");
      out.write("          <a class=\"dropdown-item\" href=\"404.html\">404 Page</a>\n");
      out.write("          <a class=\"dropdown-item\" href=\"blank.html\">Blank Page</a>\n");
      out.write("        </div>\n");
      out.write("      </li>\n");
      out.write("      <li class=\"nav-item\">\n");
      out.write("        <a class=\"nav-link\" href=\"charts.html\">\n");
      out.write("          <i class=\"fas fa-fw fa-chart-area\"></i>\n");
      out.write("          <span>Charts</span></a>\n");
      out.write("      </li>\n");
      out.write("      <li class=\"nav-item\">\n");
      out.write("        <a class=\"nav-link\" href=\"tables.html\">\n");
      out.write("          <i class=\"fas fa-fw fa-table\"></i>\n");
      out.write("          <span>Tables</span></a>\n");
      out.write("      </li>\n");
      out.write("    </ul>\n");
      out.write("\n");
      out.write("    <div id=\"content-wrapper\">\n");
      out.write("\n");
      out.write("      <div class=\"container-fluid\">\n");
      out.write("\n");
      out.write("        <!-- Breadcrumbs-->\n");
      out.write("        <ol class=\"breadcrumb\">\n");
      out.write("          <li class=\"breadcrumb-item\">\n");
      out.write("            <a href=\"#\">Dashboard</a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"breadcrumb-item active\">Overview</li>\n");
      out.write("        </ol>\n");
      out.write("\n");
      out.write("        <!-- Icon Cards-->\n");
      out.write("        <div class=\"row\">\n");
      out.write("          <div class=\"col-xl-3 col-sm-6 mb-3\">\n");
      out.write("            <div class=\"card text-white bg-primary o-hidden h-100\">\n");
      out.write("              <div class=\"card-body\">\n");
      out.write("                <div class=\"card-body-icon\">\n");
      out.write("                  <i class=\"fas fa-fw fa-comments\"></i>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"mr-5\">26 New Messages!</div>\n");
      out.write("              </div>\n");
      out.write("              <a class=\"card-footer text-white clearfix small z-1\" href=\"#\">\n");
      out.write("                <span class=\"float-left\">View Details</span>\n");
      out.write("                <span class=\"float-right\">\n");
      out.write("                  <i class=\"fas fa-angle-right\"></i>\n");
      out.write("                </span>\n");
      out.write("              </a>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"col-xl-3 col-sm-6 mb-3\">\n");
      out.write("            <div class=\"card text-white bg-warning o-hidden h-100\">\n");
      out.write("              <div class=\"card-body\">\n");
      out.write("                <div class=\"card-body-icon\">\n");
      out.write("                  <i class=\"fas fa-fw fa-list\"></i>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"mr-5\">11 New Tasks!</div>\n");
      out.write("              </div>\n");
      out.write("              <a class=\"card-footer text-white clearfix small z-1\" href=\"#\">\n");
      out.write("                <span class=\"float-left\">View Details</span>\n");
      out.write("                <span class=\"float-right\">\n");
      out.write("                  <i class=\"fas fa-angle-right\"></i>\n");
      out.write("                </span>\n");
      out.write("              </a>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"col-xl-3 col-sm-6 mb-3\">\n");
      out.write("            <div class=\"card text-white bg-success o-hidden h-100\">\n");
      out.write("              <div class=\"card-body\">\n");
      out.write("                <div class=\"card-body-icon\">\n");
      out.write("                  <i class=\"fas fa-fw fa-shopping-cart\"></i>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"mr-5\">123 New Orders!</div>\n");
      out.write("              </div>\n");
      out.write("              <a class=\"card-footer text-white clearfix small z-1\" href=\"#\">\n");
      out.write("                <span class=\"float-left\">View Details</span>\n");
      out.write("                <span class=\"float-right\">\n");
      out.write("                  <i class=\"fas fa-angle-right\"></i>\n");
      out.write("                </span>\n");
      out.write("              </a>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"col-xl-3 col-sm-6 mb-3\">\n");
      out.write("            <div class=\"card text-white bg-danger o-hidden h-100\">\n");
      out.write("              <div class=\"card-body\">\n");
      out.write("                <div class=\"card-body-icon\">\n");
      out.write("                  <i class=\"fas fa-fw fa-life-ring\"></i>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"mr-5\">13 New Tickets!</div>\n");
      out.write("              </div>\n");
      out.write("              <a class=\"card-footer text-white clearfix small z-1\" href=\"#\">\n");
      out.write("                <span class=\"float-left\">View Details</span>\n");
      out.write("                <span class=\"float-right\">\n");
      out.write("                  <i class=\"fas fa-angle-right\"></i>\n");
      out.write("                </span>\n");
      out.write("              </a>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Area Chart Example-->\n");
      out.write("        <div class=\"card mb-3\">\n");
      out.write("          <div class=\"card-header\">\n");
      out.write("            <i class=\"fas fa-chart-area\"></i>\n");
      out.write("            시간별 픽업 area chart</div>\n");
      out.write("          <div class=\"card-body\">\n");
      out.write("            <canvas id=\"myAreaChart\" width=\"100%\" height=\"30\"></canvas>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"card-footer small text-muted\">Updated yesterday at 11:59 PM</div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    \n");
      out.write("        <div class=\"card mb-4\">\n");
      out.write("          <div class=\"card-header\">\n");
      out.write("            <i class=\"fas fa-chart-area\"></i>\n");
      out.write("            주문-픽업 소요시간 pie chart</div>\n");
      out.write("          <div class=\"card-body\">\n");
      out.write("            <canvas id=\"myBarChart\" width=\"100%\" height=\"30\"></canvas>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"card-footer small text-muted\">Updated yesterday at 11:59 PM</div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("      </div>\n");
      out.write("      <!-- /.container-fluid -->\n");
      out.write("\n");
      out.write("      <!-- Sticky Footer -->\n");
      out.write("      <footer class=\"sticky-footer\">\n");
      out.write("        <div class=\"container my-auto\">\n");
      out.write("          <div class=\"copyright text-center my-auto\">\n");
      out.write("            <span>Copyright © Your Website 2019</span>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </footer>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("    <!-- /.content-wrapper -->\n");
      out.write("\n");
      out.write("  </div>\n");
      out.write("  <!-- /#wrapper -->\n");
      out.write("\n");
      out.write("  <!-- Scroll to Top Button-->\n");
      out.write("  <a class=\"scroll-to-top rounded\" href=\"#page-top\">\n");
      out.write("    <i class=\"fas fa-angle-up\"></i>\n");
      out.write("  </a>\n");
      out.write("\n");
      out.write("  <!-- Logout Modal-->\n");
      out.write("  <div class=\"modal fade\" id=\"logoutModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\n");
      out.write("    <div class=\"modal-dialog\" role=\"document\">\n");
      out.write("      <div class=\"modal-content\">\n");
      out.write("        <div class=\"modal-header\">\n");
      out.write("          <h5 class=\"modal-title\" id=\"exampleModalLabel\">Ready to Leave?</h5>\n");
      out.write("          <button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("            <span aria-hidden=\"true\">×</span>\n");
      out.write("          </button>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"modal-body\">Select \"Logout\" below if you are ready to end your current session.</div>\n");
      out.write("        <div class=\"modal-footer\">\n");
      out.write("          <button class=\"btn btn-secondary\" type=\"button\" data-dismiss=\"modal\">Cancel</button>\n");
      out.write("          <a class=\"btn btn-primary\" href=\"login.html\">Logout</a>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <!-- Bootstrap core JavaScript-->\n");
      out.write("  <script src=\"/resources/bootstrap/vendor/jquery/jquery.min.js\"></script>\n");
      out.write("  <script src=\"/resources/bootstrap/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("\n");
      out.write("  <!-- Core plugin JavaScript-->\n");
      out.write("  <script src=\"/resources/bootstrap/vendor/jquery-easing/jquery.easing.min.js\"></script>\n");
      out.write("\n");
      out.write("  <!-- Page level plugin JavaScript-->\n");
      out.write("  <script src=\"/resources/bootstrap/vendor/chart.js/Chart.min.js\"></script>\n");
      out.write("  <script src=\"/resources/bootstrap/vendor/datatables/jquery.dataTables.js\"></script>\n");
      out.write("  <script src=\"/resources/bootstrap/vendor/datatables/dataTables.bootstrap4.js\"></script>\n");
      out.write("\n");
      out.write("  <!-- Custom scripts for all pages-->\n");
      out.write("  <script src=\"/resources/bootstrap/js/sb-admin.min.js\"></script>\n");
      out.write("\n");
      out.write("  <!-- Demo scripts for this page-->\n");
      out.write("  <script src=\"/resources/bootstrap/js/demo/datatables-demo.js\"></script>\n");
      out.write("  <!--  <script src=\"/resources/bootstrap/js/demo/chart-area-demo.js\"></script>-->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("  <!-- charJS start!!!!!!!! -->\n");
      out.write("\t<script src=\"/resources/bootstrap/js/demo/pickUpArea.js\"></script>\n");
      out.write("\t<script src=\"/resources/bootstrap/js/demo/pickUpBar.js\"></script>\n");
      out.write("\n");
      out.write("<!--  Area Chart!!!!!!!!!!! -->\n");
      out.write("<!-- \n");
      out.write("  <script>\n");
      out.write("  var ctx = document.getElementById(\"myChart\");\n");
      out.write("  var chartLabels = [];\n");
      out.write("  var chartData1 = [];\n");
      out.write("  \n");
      out.write("  \n");
      out.write("  var myLineChart = new Chart(ctx, {\n");
      out.write("\t  type: 'line',\n");
      out.write("\t  data: {\n");
      out.write("\t    labels: [\"10:00\", \"11:00\", \"12:00\", \"13:00\", \"14:00\", \"15:00\", \"16:00\", \"17:00\", \"18:00\", \"19:00\", \"20:00\", \"21:00\", \"22:00\",\"23:00\"],\n");
      out.write("\t    datasets: [{\n");
      out.write("\t      label: \"픽업건수\",\n");
      out.write("\t      lineTension: 0.3,\n");
      out.write("\t      backgroundColor: \"rgba(2,117,216,0.2)\",\n");
      out.write("\t      borderColor: \"rgba(2,117,216,1)\",\n");
      out.write("\t      pointRadius: 5,\n");
      out.write("\t      pointBackgroundColor: \"rgba(2,117,216,1)\",\n");
      out.write("\t      pointBorderColor: \"rgba(255,255,255,0.8)\",\n");
      out.write("\t      pointHoverRadius: 5,\n");
      out.write("\t      pointHoverBackgroundColor: \"rgba(2,117,216,1)\",\n");
      out.write("\t      pointHitRadius: 50,\n");
      out.write("\t      pointBorderWidth: 2,\n");
      out.write("\t      data: [");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${t10}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${t11}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${t12}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${t13}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${t14}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${t15}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${t16}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${t17}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${t18}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${t19}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${t20}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${t21}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${t22}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${t23}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("],\n");
      out.write("\t    }],\n");
      out.write("\t  },\n");
      out.write("\t  options: {\n");
      out.write("\t    scales: {\n");
      out.write("\t      xAxes: [{\n");
      out.write("\t        time: {\n");
      out.write("\t          unit: 'date'\n");
      out.write("\t        },\n");
      out.write("\t        gridLines: {\n");
      out.write("\t          display: true\n");
      out.write("\t        },\n");
      out.write("\t        ticks: {\n");
      out.write("\t          maxTicksLimit: 7\n");
      out.write("\t        }\n");
      out.write("\t      }],\n");
      out.write("\t      yAxes: [{\n");
      out.write("\t        ticks: {\n");
      out.write("\t          min: 0,\n");
      out.write("\t          max: 300,\n");
      out.write("\t          maxTicksLimit: 5\n");
      out.write("\t        },\n");
      out.write("\t        gridLines: {\n");
      out.write("\t          color: \"rgba(0, 0, 0, .125)\",\n");
      out.write("\t        }\n");
      out.write("\t      }],\n");
      out.write("\t    },\n");
      out.write("\t    legend: {\n");
      out.write("\t      display: true\n");
      out.write("\t    }\n");
      out.write("\t  }\n");
      out.write("\t});\n");
      out.write("  </script>\n");
      out.write("  -->\n");
      out.write("  <!-- My Doughnut Chart -->\n");
      out.write("\n");
      out.write(" \n");
      out.write(" \n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
